services:
  redis:
    image: redis:alpine
    restart: unless-stopped

  searxng:
    image: searxng/searxng:latest
    depends_on:
      - redis
    ports:
      - "8080:8080"
    environment:
      - SEARXNG_BASE_URL=http://127.0.0.1:8080/
      - SEARXNG_REDIS_URL=redis://redis:6379/0
      - UWSGI_WORKERS=2
      - BIND_ADDRESS=0.0.0.0
    volumes:
      - ./settings.yml:/etc/searxng/settings.yml:ro
    restart: unless-stopped
